# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/abstract-sdk
    steps:
      - checkout
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - .yarn-cache

  install:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/abstract-sdk
    steps:
      - attach_workspace:
          at: ~/abstract-sdk
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            - v2-dependencies- # fallback to latest cache if no exact match is found
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - .yarn-cache

  test:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/abstract-sdk
    steps:
      - attach_workspace:
          at: ~/abstract-sdk
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            - v2-dependencies- # fallback to latest cache if no exact match is found
      - run: yarn ci

  deploy:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/abstract-sdk
    steps:
      - attach_workspace:
          at: ~/abstract-sdk
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            - v2-dependencies- # fallback to latest cache if no exact match is found
      - run: sh .circleci/deploy

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - install:
          requires:
            - checkout
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master